LeaveManagement/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^login/$', auth_views.login, {'template_name': 'core/login.html', 'redirect_authenticated_user': True}, name='login'),
    url(r'^logout/$', auth_views.logout, {'template_name': 'core/logout.html'}, name='logout'),
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('users.urls')),
    url(r'^', include('core.urls')),
]

core/urls.py
from django.conf.urls import url
from . import views

app_name = 'core'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^add/team/$', views.add_team_form, name='add_team_form'),
    url(r'^team/detail$', views.team_detail, name='team_detail'),
]

users/urls.py
from django.conf.urls import url
from . import views

app_name = 'users'

urlpatterns = [
    url(r'^dashboard/', views.dashboard, name='dashboard'),
    url(r'^hr/dashboard/', views.hr_dashboard, name='hr_dashboard'),
    url(r'^manager/dashboard/', views.manager_dashboard, name='manager_dashboard'),
    url(r'^employee/dashboard/', views.employee_dashboard, name='employee_dashboard'),
]

core/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


class Team(models.Model):
    name = models.CharField(max_length=127, blank=True, null=True)
    description = models.TextField(max_length=255, blank=True, null=True)

    class Meta:
        verbose_name = _('team')

    def __unicode__(self):
        return self.name

users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils.translation import ugettext_lazy as _

from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.db import models
from django.core.mail import send_mail
from django.core import validators


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Creates and saves a User with the given email and password.
        :param email:
        :param password:
        :param extra_fields:
        :return:
        """
        if not email:
            raise ValueError("The given email must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_staff', True)

        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser = True')

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff = True')

        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    LEVEL1 = 1
    LEVEL2 = 2
    LEVEL3 = 3

    USER_TYPE = (
        (LEVEL1, 'HR'),
        (LEVEL2, 'Manager'),
        (LEVEL3, 'Employee')
    )
    # username = models.CharField(_('username'), max_length=60, unique=True,
    #                             help_text=_('Required. 60 characters or fewer. Letters, digits and '
    #                                         '@/./+/-/_ only.'),
    #                             validators=[
    #                                 validators.RegexValidator(r'^[\w.@+-]+$',
    #                                                           _('Enter a valid username. '
    #                                                             'This value may contain only letters, numbers '
    #                                                             'and @/./+/-/_ characters.'), 'invalid'),
    #                             ],
    #                             error_messages={
    #                                 'unique': _("A user with that username already exists."),
    #                             })
    email = models.EmailField(_('email address'), unique=True)
    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=30, blank=True)
    is_active = models.BooleanField(_('active'), default=True)
    is_staff = models.BooleanField(_('staff status'), default=False,
                                   help_text=_('Designates whether the user can log into this master site.'))
    type = models.IntegerField(_('User Type'), choices=USER_TYPE, default=LEVEL3)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def get_full_name(self):
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name

    def get_short_name(self):
        return self.first_name

    def email_user(self, subject, message, from_mail=None, **kwargs):
        send_mail(subject, message, from_mail, [self.email], **kwargs)

    @property
    def is_hr(self):
        return self.type == self.LEVEL1

    @property
    def is_manager(self):
        return self.type == self.LEVEL2

    @property
    def is_employee(self):
        return self.type == self.LEVEL3

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User


# class MyUserCreationForm(UserCreationForm):
#     type = forms.ChoiceField(label='User Type', choices=User.USER_TYPE,
#                                                 widget=forms.Select(attrs={'class': "form-control"}))
#
#     class Meta:
#         model = User
#         fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2', 'type')

core/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, reverse
from django.http import HttpResponseRedirect


def index(request):
    curr_user = request.user

    if curr_user.is_authenticated():
        return HttpResponseRedirect(reverse('users:dashboard'))
    else:
        return HttpResponseRedirect(reverse('login'))


def add_team_form(request):
    print "In add team form"
    return render(request, 'core/addTeamForm.html')


def team_detail(request):
    pass

users/views.py
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import Http404
from django.http.response import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse


@login_required
def dashboard(request):
    curr_user = request.user
    if curr_user.is_hr:
        return HttpResponseRedirect(reverse('users:hr_dashboard'))
    elif curr_user.is_manager:
        return HttpResponseRedirect(reverse('users:manager_dashboard'))
    elif curr_user.is_employee:
        return HttpResponseRedirect(reverse('users:employee_dashboard'))
    else:
        return Http404


@login_required
def hr_dashboard(request):
    return render(request, 'users/hr_dashboard.html')


@login_required
def manager_dashboard(request):
    return render(request, 'users/manager_dashboard.html')


@login_required
def employee_dashboard(request):
    return render(request, 'users/employee_dashboard.html')

templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Login{% endblock %}</title>
</head>
<body>
  <header>
    <h1>Django Simple Login</h1>
    {% if user.is_authenticated %}
      Hi {{ user.username }}!
      <a href="{% url 'logout' %}">logout</a>
    {% else %}
      <a href="{% url 'login' %}">login</a>
    {% endif %}
  </header>
  <hr>
  <main>
    {% block content %}
    {% endblock %}
  </main>
  <hr>
</body>
</html>

templates/core/addTeamForm.html
{% extends 'base.html' %}

{% block title %}Add Team{% endblock %}

{% block content %}
    <div class="container" xmlns="http://www.w3.org/1999/html">
        <div class="col-sm-4"></div>
        <div class="col-sm-8">
            <form id="addTeam" action="{% url 'core:team_detail' %}" method="post">
                {% csrf_token %}
                <label for="team-name">Team Name : </label>
                <input type="text" name="team-name" id="team-name" /><br>
                <label for="team-desc">Team Description : </label>
                <textarea name="team-desc" id="team-desc"></textarea>
                <input type="submit" name="submit" value="Submit">
            </form>
        </div>
        <div class="col-sm-4"></div>
    </div>
{% endblock content %}

templates/core/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
{% endblock %}

templates/core/logout.html
{% extends 'base.html' %}

{% block title %}See you!{% endblock %}

{% block content %}
  <h2>Logged out</h2>
  <p>You have been successfully logged out.</p>
  <p><a href="{% url 'login' %}">Log in</a> again.</p>
{% endblock %}

templates/users/employee_dashboard.html
{% extends 'base.html' %}

{% block title %}Employee{% endblock %}

{% block content %}
  <h2>You are Employee</h2>
{% endblock %}

templates/users/hr_dashboard.html
{% extends 'base.html' %}

{% block title %}HR{% endblock %}

{% block content %}
    <div class="container">
        <div class="col-sm-4">
            <a class="btn btn-info" type="button" href="{% url 'core:add_team_form' %}">Add Team</a>
        </div>
        <div class="col-sm-8">
            <h2>You are HR</h2>
        </div>
        <div class="col-sm-4">
        </div>
    </div>
{% endblock %}

templates/users/manager_dashboard.html
{% extends 'base.html' %}

{% block title %}Manager{% endblock %}

{% block content %}
  <h2>You are manager</h2>
{% endblock %}